### ISSUE TITLE
Example application doesn't run on Node 13

### ISSUE THREAD

**Issue by electrified** [HMPO/hmpo-form-wizard#150]
```
 % npm start
> demo-form@1.0.0 start /home/ed/dev/passports-form-wizard/example
> node app.js

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/home/ed/dev/passports-form-wizard/example/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/ed/dev/passports-form-wizard/example/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/ed/dev/passports-form-wizard/example/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by HughePaul** [comment]
Updated example
